chore: 添加贡献指南
proskynova/proskynova.github.io pull request #14
Opened 2024-02-24 15:20 UTC by Zh40Le1ZOOB

2024-02-27 06:06 UTC, Cryolitia requested changes

2024-02-27 06:06 UTC, Cryolitia commented on CONTRIBUTING.md
> +Footer 部分用于承载额外内容，如关闭某个（或多个） issue
```suggestion
Footer 部分用于承载额外内容，如关闭某个（或多个） issue，签名行。
```

2024-02-27 06:06 UTC, Cryolitia commented on CONTRIBUTING.md
> +Closes #1, #2, #3
```suggestion
Resolves #1, resolves #2, resolves #3
Signed-off-by: Someone <someone@example.com>
```
https://docs.github.com/zh/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2024-02-27 06:06 UTC, Cryolitia commented on CONTRIBUTING.md
> +Revert 提交的 Header 部分应以 `revert: ` 开头，后接被 revert 的提交的 Header，其 Body 部分应只有 `This reverts commit <hash>.`，`<hash>` 是被 revert 的提交的 SHA。
```suggestion
Revert 提交的 Header 部分应以 `revert: ` 开头，后接被 revert 的提交的 Header，其 Body 部分应有 `This reverts commit <hash>.`，`<hash>` 是被 revert 的提交的 SHA，可以附加revert的理由。
```

2024-02-27 10:01 UTC, Cryolitia commented on CONTRIBUTING.md
> +> 提交说明的所有格式部分均使用英文半角标点，只有字段内容视使用语言使用全角标点。所有中文部分应遵守盘古之白（在 CJK 字符与英文之间插入空格）。
说实话我觉得盘古之白是排版问题，空格是语义化分词问题，把这两个混淆非常不妥。

盘古之白是软件在 **渲染时** 插入1/4em，而不是在文本中直接插入空格。

commit信息更多的是语义化考虑，例如 `docs: 更新贡献者指南`，这里的`: `共同作为语义化的分割而非单纯出于美观考虑。

2024-02-27 10:04 UTC, Zh40Le1ZOOB commented on CONTRIBUTING.md
> +> 提交说明的所有格式部分均使用英文半角标点，只有字段内容视使用语言使用全角标点。所有中文部分应遵守盘古之白（在 CJK 字符与英文之间插入空格）。
但还是考虑到美观和可读性问题，我认为盘古之白是有必要的，毕竟浏览器不会自己给你分开，Shell 里看 git log 时也会是挤在一起的

2024-02-27 23:28 UTC, Cryolitia requested changes

2024-02-27 23:28 UTC, Cryolitia commented on CONTRIBUTING.md
> +> 提交说明的所有格式部分均使用英文半角标点，只有字段内容视使用语言使用全角标点。所有中文部分应遵守盘古之白（在 CJK 字符与英文之间插入空格）。
```suggestion
> 提交说明的所有格式部分均使用英文半角标点，只有字段内容视使用语言使用全角标点，所有 CJK 字符与英文之间应插入空格。
```

2024-02-29 07:24 UTC, Cryolitia approved these changes

2024-02-29 07:25 UTC, merged